run_name: base_calms
model_name: "facebook/vjepa2-vitl-fpc32-256-diving48"
predict_per_item: 64
model:
  fc_drop_rate: 0.5
  class_weights: inv_freq_sqrt
  freeze_encoder_layers: 12
data:
  prefix: "/home/petr/home_datasets/reencoded_calms"
  label_json: "/data/petr/caltech_mice/new_calms_labels.json"
  chunk_length: 64
  chunk_shift: 32
  chunk_step: 1
  resize_to: 256
  do_aa: true
training:
  epochs: 10
  train_bs: 4
  val_bs: 8
  num_workers: 12
  part_warmup: 0.2
  lr: 4.0e-5
  weight_decay: 0.1
  label_smoothing: 0.1
  compile: true
mixup_alpha: 0.8
ema_decay: 0.999
seed: 0
device: "cuda"
wandb:
  key: dde17687b4b84ba8171dfede64d865243be41a0e
  entity: sposiboh
  project: feral_public