run_name: calms_again_half
model_name: "HuggingFaceTB/SmolVLM2-500M-Instruct"
predict_per_item: 16
model:
  fc_drop_rate: 0.5
  drop_path: 0
  head_drop_path: 0
  freeze_layers: 0
  freeze_embeddings: true
  backbone_dropout: 0
  class_weights: inv_freq_sqrt
data:
  prefix: "/mnt/aperto/peter/feral_data/calms/reencoded"
  label_json: "/mnt/aperto/peter/feral_data/calms/half_labels.json"
  chunk_length: 16
  chunk_shift: 8
  resize_to: 256
  do_aa: true
training:
  epochs: 10
  train_bs: 16
  val_bs: 32
  num_workers: 10
  warmup_epochs: 2
  lr: 4.0e-5
  weight_decay: 0.1
  label_smoothing: 0.1
mixup_alpha: 0.8
ema_decay: 0.999
seed: 0
device: "cuda:3"